variables:
  MONGO_DB_DATABASE: $MONGO_DB_DATABASE
  MONGO_DB_ROOT_USERNAME: $MONGO_DB_ROOT_USERNAME
  MONGO_DB_ROOT_PASSWORD: $MONGO_DB_ROOT_PASSWORD
  MONGO_DB_HOST: mongodb+srv://${MONGO_DB_ROOT_USERNAME}:${MONGO_DB_ROOT_PASSWORD}@cluster0.1viz4.mongodb.net/

default:
  image: python:3.13.1
  services:
    - name: pymongo:4.11.3
      alias: pymongo
  cache:
    paths:
      - ~/.cache/pip
  before_script:
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install flake8

migrate:
  stage: build
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check

lint:
  stage: lint
  script:
    - echo "Running flake8 linting..."
    - flake8 src/timelinextract/
  allow_failure: false

test:
  stage: test
  script:
    - echo "Running Django system checks and tests..."
    - python3 manage.py check
    - python3 manage.py test
  variables:
    DJANGO_SETTINGS_MODULE: timelinextract.settings

deploy:
  stage: deploy
  script:
    - echo "Define your deployment steps here!"
    - echo "No deployment for now"
  environment: production

