default:
  image: python:3.13.1
  cache:
    paths:
      - ~/.cache/pip
  before_script:
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install flake8

build:
  stage: build
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check

test:
  stage: test
  script:
    - echo "Running Django system checks and tests..."
    - python3 manage.py check
    - python3 manage.py test
    - echo "Running flake8 linting..."
    - flake8 src/timelinextract/
  variables:
    DJANGO_SETTINGS_MODULE: timelinextract.settings

deploy:
  stage: deploy
  script:
    - echo "Define your deployment steps here!"
    - echo "No deployment for now"
  environment: production

