from django.test import TestCase
from srcExtractor.tests.test_data_processing import DataProcessingTests
from srcExtractor.tests.test_data_validation import DataValidationTests
from srcExtractor.tests.test_file_handler import FileHandlerTests
from srcExtractor.tests.test_match_questionnaires import MatchQuestionnairesTests
from srcExtractor.tests.test_pdf_processing import PDFProcessingTests
from srcExtractor.tests.test_pdf_validation import PDFUploadTests
from srcExtractor.tests.test_user_mongodb import UserMongoDBTests
from srcExtractor.tests.test_pdf_mongodb import PDFMongoDBTests
from srcExtractor.tests.test_query_mongodb import QueryMongoDBTests
from srcExtractor.tests.test_table_mongodb import TablesMongoDBTests
from srcExtractor.tests.test_output_mongodb import OutputMongoDBTests

# All srcExtractor tests are in the tests folder
